Update
Centrunk/dvm_cm pull request #14
Opened 2023-07-01 05:16 UTC by Nine-JuanJuan

Converted to DVM3.5 templates. Added options in inventory.example for updates. Will need to review

2023-07-01 05:16 UTC, Nine-JuanJuan commented
@lastation4 Review changes before merging

2023-07-02 17:35 UTC, faultywarrior commented on playbooks/ctrs-installer.yml
amd64 fix is half-correct.  We still need to do the ansible search for x86_64.

2023-07-02 17:46 UTC, faultywarrior approved these changes
lgtm

2023-07-02 17:57 UTC, lastation4 requested changes
changes need to be made, I'll make them and re-commit

2023-07-02 17:57 UTC, lastation4 commented on playbooks/ctrs-installer.yml
> +      when: ansible_architecture is search("amd64")
This needs to be reverted back to

"x86_64"

2023-07-02 17:57 UTC, lastation4 commented on playbooks/ctrs-installer.yml
> +      when: ansible_architecture is search("amd64")
This needs to be reverted back to

"x86_64"

2023-07-02 18:00 UTC, closed without merging